import './globals.css';
import Navbar from '@/components/navbar';
import Provider from '@/components/provider';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang='en' className='max-h-fit'>
      <body className='max-w-screen flex flex-wrap flex-row justify-center text-black bg-gray'>
        <Provider>
          <div className='h-[10vh] basis-full flex self-start max-w-screen'>
            <Navbar />
          </div>
          <div id='root-layout' className='basis-full max-w-full flex flex-wrap flex-row items-center justify-center'>
            {children}
          </div>
        </Provider>
      </body>
    </html>
  )
}