import './globals.css';
import Navbar from '@/components/navbar';
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className='flex flex-wrap flex-row bg-black text-white'>
        <div className='h-[8vh] basis-full flex self-start'>
          <Navbar />
        </div>
        <div className='h-[92vh] basis-full flex flex-col items-center justify-center bg-gray-900'>
          {children}
        </div>
      </body>
    </html>
  )
}